# -*- coding: utf-8 -*-
"""model_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pevyXxFKY8p72eOfKWmX1QOHXWwjkVZ
"""

from transformers import Blip2Processor, Blip2ForConditionalGeneration
import torch

def load_blip2():
    processor = Blip2Processor.from_pretrained("Salesforce/blip2-flan-t5-xl")
    model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xl", device_map="auto")
    return processor, model

def extract_structured_data(image, processor, model):
    prompt = "Extract doctor name, patient name, medicines, dosage, and instructions from this prescription. Return as JSON."
    inputs = processor(images=image, text=prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_new_tokens=300)
    result = processor.decode(output[0], skip_special_tokens=True)
    return result