# -*- coding: utf-8 -*-
"""run_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pevyXxFKY8p72eOfKWmX1QOHXWwjkVZ
"""

# Create this file manually with your labels.

# ---------- run_pipeline.py ----------
!pip install src
import os, json , src
from src.preprocess import preprocess_image
from src.model_utils import load_blip2, extract_structured_data

image_dir = "data"
processor, model = load_blip2()
results = []

for filename in os.listdir(image_dir):
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img_path = os.path.join(image_dir, filename)
        image = preprocess_image(img_path)
        result = extract_structured_data(image, processor, model)
        results.append({"file": filename, "result": result})

with open("results.json", "w") as f:
    json.dump(results, f, indent=2)